# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kate Bowie
tagline:          "Personal Website"
description:      "Writing words, and looking good doing it"
url:              http://katebowie.com/
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

alex: https://github.com/ouked

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
